"""empty message

Revision ID: 0137e410cbea
Revises: 5d0f7b0e20fa
Create Date: 2021-01-02 17:18:49.261965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0137e410cbea'
down_revision = '5d0f7b0e20fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('apple_music_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('bandcamp_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('reddit_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('soundcloud_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('spotify_url', sa.String(), nullable=True))
    op.add_column('creative', sa.Column('twitter_url', sa.String(), nullable=True))
    op.drop_column('creative', 'twitter_username')
    op.drop_column('creative', 'facebook_username')
    op.drop_column('creative', 'instagram_username')
    op.drop_column('creative', 'bandcamp_username')
    op.drop_column('creative', 'reddit_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('reddit_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('creative', sa.Column('bandcamp_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('creative', sa.Column('instagram_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('creative', sa.Column('facebook_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('creative', sa.Column('twitter_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('creative', 'twitter_url')
    op.drop_column('creative', 'spotify_url')
    op.drop_column('creative', 'soundcloud_url')
    op.drop_column('creative', 'reddit_url')
    op.drop_column('creative', 'instagram_url')
    op.drop_column('creative', 'facebook_url')
    op.drop_column('creative', 'bandcamp_url')
    op.drop_column('creative', 'apple_music_url')
    # ### end Alembic commands ###
