"""empty message

Revision ID: 218bf18152a6
Revises: d71c795cabbe
Create Date: 2021-01-22 21:03:15.754811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218bf18152a6'
down_revision = 'd71c795cabbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_media',
    sa.Column('creative_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['creative.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creative_media')
    # ### end Alembic commands ###
