"""empty message

Revision ID: 401a20c91215
Revises: e5581bbcdf27
Create Date: 2021-01-23 10:12:01.246572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401a20c91215'
down_revision = 'e5581bbcdf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creative', 'about',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creative', 'about',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
