"""empty message

Revision ID: 5d0f7b0e20fa
Revises: 7f0fd124b796
Create Date: 2021-01-02 16:35:14.825082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0f7b0e20fa'
down_revision = '7f0fd124b796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('creative', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('creative', 'profile_image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'creative', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creative', type_='foreignkey')
    op.alter_column('creative', 'profile_image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('creative', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
