"""empty message

Revision ID: 64faf1a1d3bf
Revises: 401a20c91215
Create Date: 2021-01-23 10:16:10.006920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64faf1a1d3bf'
down_revision = '401a20c91215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creative', 'is_admin')
    # ### end Alembic commands ###
