"""empty message

Revision ID: 9fac6a7d316c
Revises: 0137e410cbea
Create Date: 2021-01-19 01:20:58.006164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fac6a7d316c'
down_revision = '0137e410cbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('is_homepage', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_creative_is_homepage'), 'creative', ['is_homepage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_is_homepage'), table_name='creative')
    op.drop_column('creative', 'is_homepage')
    # ### end Alembic commands ###
