"""empty message

Revision ID: d71c795cabbe
Revises: 9fac6a7d316c
Create Date: 2021-01-19 01:40:49.208457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71c795cabbe'
down_revision = '9fac6a7d316c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('profile_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'media', ['profile_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'profile_image_id')
    # ### end Alembic commands ###
