"""empty message

Revision ID: e5581bbcdf27
Revises: 65f0e887277d
Create Date: 2021-01-23 10:07:32.879012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5581bbcdf27'
down_revision = '65f0e887277d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creative', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('creative', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'creative', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creative', type_='unique')
    op.alter_column('creative', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('creative', 'password')
    # ### end Alembic commands ###
